### ISSUE TITLE
Document init containers and migrations

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1056]
That's how we run `migrate` and similar scripts in real-life:

```yml
initContainers:
  - args:
      - ...
    command:
      - ...
    envFrom:
      - configMapRef:
        name: django-env-map
    image:
    imagePullPolicy: Always
    name: django_bundle
    volumeMounts:
      - mountPath: /var/www/django
        name: volume-hzlzw
      - mountPath: /code/locale
        name: locale
```
