### ISSUE TITLE
Update to poetry@1.1

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#1328]
We should also change:
```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
