### ISSUE TITLE
Add explicit pgdata volume

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#55]
```yaml
services:
  db:
    ...
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  django-static:
```
