### ISSUE TITLE
Consider using gitlab checks

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-django-template#559]
Since Gitlab 11.2 there are new keyword in CI file - `atrifacts:reports`.

There are a lot of [checks](https://docs.gitlab.com/ee/ci/yaml/README.html#artifactsreports).
Some of them might be interesting enough to add them in to template. Like:
* Code quality check
* Dependency vulnerabilities check
* Docker container check
* Dependency licenses check

Adding them should not be a problem, since it's a new job
```yaml
code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
```

There is a problem though. Volumes in gitlab are mess. Sometimes they do not works as expected (see [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/41227#note_52029664))
