### ISSUE TITLE
Build tagged images on git tags

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#576]
Currently our workflow looks like this:

```yaml
release-image:
  stage: deploy
  script:
    - docker build -t "$CONTAINER_RELEASE_IMAGE"
      --build-arg DJANGO_ENV=production -f docker/django/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master
  environment:
    name: production  # used to track time with 'cycle analytics'
```

Where `CONTAINER_RELEASE_IMAGE` equals to `"$REGISTRY/$GROUP_NAME/$PROJECT_NAME:latest"`.

But, that an anti-pattern. Because we always use `latest` for version numbers. There's no default way to build versioned images like: `"$REGISTRY/$GROUP_NAME/$PROJECT_NAME:3.5"`.

And I suggest to fix it with `git tag`. I already use it in our workflow, we just need to set appropriate tag names when new `tag` is pushed. We can use `CI_COMMIT_TAG` with a simple condition. https://docs.gitlab.com/ee/ci/variables/

**Comment by sobolevn** [comment]
@AlwxSin what do you think? Do you use tags in your workflow?

**Comment by AlwxSin** [comment]
No, we don't. I like Denis Stebunov's way. If there are problems in production we made new fix.

I don't think that tagging should be in template, it's out of scope. Similar to #547

**Comment by sobolevn** [comment]
This might help to integrate several services together. There are usecases when other images require different image versions.

Like microservices, frontend/backed, etc.

**Comment by sobolevn** [comment]
After some tests I came up with this solution:

```yaml
---

image: docker:latest

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance:
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: "git_tag"
  GROUP_NAME: "sobolevn"
  REGISTRY: "registry.gitlab.com"
  CONTAINER_RELEASE_IMAGE: "$REGISTRY/$GROUP_NAME/$PROJECT_NAME"

services:
  - docker:dind

before_script:
  # Installing docker-compose:
  - apk update && apk upgrade
  - apk add python python-dev py-pip git build-base
  - pip install dump-env docker-compose
  # Creating `.env` configuration file:
  - dump-env -t config/.env.template -p 'SECRET_' > config/.env
  # Login into Docker registry:
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$REGISTRY"
  # Debug information:
  - docker info && docker-compose --version && git --version

# Testing application:
test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f docker/docker-compose.prod.yml
      config --quiet
    - docker-compose run web sh ./docker/ci.sh
  coverage: '/[\d\.]+\%\s*$/'

# Releasing image, when tests pass (only one at a time):
release-latest-image:
  stage: deploy
  script:
    - docker build -t "$CONTAINER_RELEASE_IMAGE:latest"
      --build-arg DJANGO_ENV=production -f docker/django/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE:latest"
  only:
    - master
  environment:
    name: production  # used to track time with 'cycle analytics'

release-tagged-image:
  stage: deploy
  script:
    # Creating tagged version:
    - docker build -t "$CONTAINER_RELEASE_IMAGE:$CI_COMMIT_TAG"
      --build-arg DJANGO_ENV=production -f docker/django/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags
  environment:
    name: production  # used to track time with 'cycle analytics'

```

But I agree with @AlwxSin it is out of scope for the global template. Since it relies heavily on your workflow and release strategies, but not on tools we provide.

**Comment by AlwxSin** [comment]
I'd also suggest to use anchors like this
```yaml
.release-image: &release-image
  stage: deploy
    script:
    - docker build -t "$CONTAINER_RELEASE_IMAGE:$TAG_NAME"
      --build-arg DJANGO_ENV=production -f docker/django/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE:$TAG_NAME"
  environment:
    name: production  # used to track time with 'cycle analytics'


# Releasing image, when tests pass (only one at a time):
release-latest-image:
  <<: *release-image
  variables:
    TAG_NAME: latest
  only:
    - master
    
release-tagged-image:
  <<: *release-image
    variables:
      TAG_NAME: $CI_COMMIT_TAG
    only:
      - tags
```
