### ISSUE TITLE
When docker is not used - pre-commit hook is useless

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-django-template#89]
```yaml
- repo: local
  hooks:
    - id: qa
      name: qa
      entry: docker-compose run -e INSIDE_CI=0 web sh ./docker/ci.sh
      pass_filenames: false
      language: system
```

It is impossible to run `docker` in this configuration. So, the tests should be run locally.
